package com.cerex.domain;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.UpdateTimestamp;
import org.hibernate.type.SqlTypes;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;

/**
 * Domain entity representing a customer order on the Cerex platform.
 *
 * <p>An Order is the financial and logistics aggregate for food purchases.
 * It supports multiple order types:
 * <ul>
 *   <li>DELIVERY — food delivered to customer's address</li>
 *   <li>PICKUP — customer collects from restaurant</li>
 *   <li>DINE_IN — order placed at restaurant table</li>
 *   <li>INGREDIENT_KIT — curated ingredients delivered for home cooking</li>
 *   <li>CATERING — bulk order for events</li>
 * </ul>
 *
 * <p>Order lifecycle:
 * <pre>
 *   PENDING → CONFIRMED → PREPARING → READY → OUT_FOR_DELIVERY → DELIVERED
 *          ↘ CANCELLED (from PENDING or CONFIRMED only)
 *   Any state → REFUNDED (after payment chargeback or dispute)
 * </pre>
 *
 * <p>The table is range-partitioned by {@code created_at} (monthly) for performance.
 *
 * @author Cerex Engineering Team
 * @version 1.0.0
 */
@Entity
@Table(
    name = "orders",
    schema = "orders_schema",
    indexes = {
        @Index(name = "idx_orders_user_id",      columnList = "user_id"),
        @Index(name = "idx_orders_restaurant_id", columnList = "restaurant_id"),
        @Index(name = "idx_orders_status",        columnList = "status"),
        @Index(name = "idx_orders_order_number",  columnList = "order_number", unique = true),
        @Index(name = "idx_orders_created_at",    columnList = "created_at"),
        @Index(name = "idx_orders_payment_intent", columnList = "payment_intent_id"),
    }
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ToString(exclude = {"items"})
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class Order {

    // ─────────────────────────────────────────────────────────────
    // Primary Key
    // ─────────────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    @EqualsAndHashCode.Include
    private UUID id;

    // ─────────────────────────────────────────────────────────────
    // Order Identification
    // ─────────────────────────────────────────────────────────────

    /**
     * Human-readable order number displayed to users.
     * Format: CRX-YYYY-XXXXXX (e.g., "CRX-2026-004521")
     * Generated by application, unique across all partitions.
     */
    @NotBlank
    @Pattern(regexp = "CRX-\\d{4}-\\d{6}", message = "Invalid order number format")
    @Column(name = "order_number", nullable = false, unique = true, length = 20)
    private String orderNumber;

    // ─────────────────────────────────────────────────────────────
    // Participants
    // ─────────────────────────────────────────────────────────────

    /** The customer who placed this order. */
    @NotNull(message = "User ID is required")
    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", insertable = false, updatable = false)
    private User user;

    /**
     * The restaurant fulfilling the order.
     * Null for INGREDIENT_KIT orders (fulfilled by Cerex).
     */
    @Column(name = "restaurant_id")
    private UUID restaurantId;

    // ─────────────────────────────────────────────────────────────
    // Order Classification
    // ─────────────────────────────────────────────────────────────

    /**
     * How the order will be fulfilled.
     * @see OrderType
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "order_type", nullable = false, length = 20)
    @Builder.Default
    private OrderType orderType = OrderType.DELIVERY;

    /**
     * Current lifecycle status of the order.
     * @see OrderStatus
     */
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    @Builder.Default
    private OrderStatus status = OrderStatus.PENDING;

    // ─────────────────────────────────────────────────────────────
    // Pricing (all amounts in minor units conceptually stored as decimals)
    // ─────────────────────────────────────────────────────────────

    /**
     * Sum of all item prices before any deductions.
     * subtotal = Σ(item.unit_price × item.quantity)
     */
    @NotNull
    @DecimalMin("0.01")
    @Column(name = "subtotal", nullable = false, precision = 12, scale = 2)
    private BigDecimal subtotal;

    /** Amount deducted via promotions or coupons. */
    @DecimalMin("0.00")
    @Column(name = "discount_amount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal discountAmount = BigDecimal.ZERO;

    /** Delivery fee charged to the customer. */
    @DecimalMin("0.00")
    @Column(name = "delivery_fee", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal deliveryFee = BigDecimal.ZERO;

    /** Platform service fee (typically 5% of subtotal). */
    @DecimalMin("0.00")
    @Column(name = "service_fee", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal serviceFee = BigDecimal.ZERO;

    /** VAT/GST/tax applied based on the delivery jurisdiction. */
    @DecimalMin("0.00")
    @Column(name = "tax_amount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal taxAmount = BigDecimal.ZERO;

    /** Optional gratuity added by the customer. */
    @DecimalMin("0.00")
    @Column(name = "tip_amount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal tipAmount = BigDecimal.ZERO;

    /**
     * Grand total charged to the customer.
     * total = subtotal - discount + delivery_fee + service_fee + tax + tip
     */
    @NotNull
    @DecimalMin("0.01")
    @Column(name = "total_amount", nullable = false, precision = 12, scale = 2)
    private BigDecimal totalAmount;

    /**
     * ISO 4217 currency code for all monetary values in this order.
     * Examples: EUR, USD, GBP, NGN, XOF
     */
    @NotBlank
    @Size(min = 3, max = 3)
    @Column(name = "currency_code", nullable = false, length = 3)
    @Builder.Default
    private String currencyCode = "EUR";

    // ─────────────────────────────────────────────────────────────
    // Delivery Details
    // ─────────────────────────────────────────────────────────────

    /**
     * Delivery destination stored as JSON.
     * Structure: {line1, line2, city, postalCode, country, latitude, longitude}
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "delivery_address", columnDefinition = "JSONB")
    private Map<String, Object> deliveryAddress;

    /** Special delivery instructions from the customer (gate code, floor, etc.). */
    @Size(max = 500)
    @Column(name = "delivery_notes", length = 500)
    private String deliveryNotes;

    /** Estimated delivery time provided to the customer at order placement. */
    @Column(name = "estimated_delivery")
    private Instant estimatedDelivery;

    /** Actual timestamp when the order was delivered. */
    @Column(name = "actual_delivery")
    private Instant actualDelivery;

    // ─────────────────────────────────────────────────────────────
    // Payment Information
    // ─────────────────────────────────────────────────────────────

    /**
     * Current payment lifecycle status.
     * @see PaymentStatus
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_status", length = 20)
    @Builder.Default
    private PaymentStatus paymentStatus = PaymentStatus.PENDING;

    /**
     * Payment method identifier.
     * Values: "stripe_card", "paypal", "apple_pay", "google_pay", "cash"
     */
    @Size(max = 50)
    @Column(name = "payment_method", length = 50)
    private String paymentMethod;

    /**
     * Stripe PaymentIntent ID for this order.
     * Used for refunds, disputes, and payment status queries.
     * Format: "pi_XXXXXXXX..."
     */
    @Size(max = 200)
    @Column(name = "payment_intent_id", length = 200)
    private String paymentIntentId;

    /** Amount refunded to the customer (partial or full). */
    @DecimalMin("0.00")
    @Column(name = "refund_amount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal refundAmount = BigDecimal.ZERO;

    /** Reason for the refund (required when refund_amount > 0). */
    @Column(name = "refund_reason", columnDefinition = "TEXT")
    private String refundReason;

    // ─────────────────────────────────────────────────────────────
    // Promotions
    // ─────────────────────────────────────────────────────────────

    /** Promo code applied at checkout (if any). */
    @Size(max = 50)
    @Column(name = "promo_code", length = 50)
    private String promoCode;

    /** Discount amount from the applied promo code. */
    @DecimalMin("0.00")
    @Column(name = "promo_discount", precision = 12, scale = 2)
    @Builder.Default
    private BigDecimal promoDiscount = BigDecimal.ZERO;

    // ─────────────────────────────────────────────────────────────
    // Delivery Tracking
    // ─────────────────────────────────────────────────────────────

    /** URL to the live order tracking page. */
    @Size(max = 500)
    @Column(name = "tracking_url", length = 500)
    private String trackingUrl;

    /** Assigned delivery driver's user ID. */
    @Column(name = "driver_id")
    private UUID driverId;

    /** Driver's display name (denormalized for tracking display). */
    @Size(max = 100)
    @Column(name = "driver_name", length = 100)
    private String driverName;

    /** Driver's masked phone number for customer contact. */
    @Size(max = 20)
    @Column(name = "driver_phone", length = 20)
    private String driverPhone;

    // ─────────────────────────────────────────────────────────────
    // Status Change Timestamps (audit trail)
    // ─────────────────────────────────────────────────────────────

    /** When the restaurant confirmed the order. */
    @Column(name = "confirmed_at")
    private Instant confirmedAt;

    /** When the restaurant started preparing the order. */
    @Column(name = "preparing_at")
    private Instant preparingAt;

    /** When the order was ready for pickup/delivery. */
    @Column(name = "ready_at")
    private Instant readyAt;

    /** When the driver picked up the order from the restaurant. */
    @Column(name = "picked_up_at")
    private Instant pickedUpAt;

    /** When the order was successfully delivered. */
    @Column(name = "delivered_at")
    private Instant deliveredAt;

    /** When the order was cancelled. */
    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    /** Reason provided for cancellation. */
    @Column(name = "cancellation_reason", columnDefinition = "TEXT")
    private String cancellationReason;

    // ─────────────────────────────────────────────────────────────
    // Standard Timestamps
    // ─────────────────────────────────────────────────────────────

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ─────────────────────────────────────────────────────────────
    // Relationships
    // ─────────────────────────────────────────────────────────────

    /** The individual items in this order. */
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("createdAt ASC")
    @Builder.Default
    private List<OrderItem> items = new ArrayList<>();

    // ─────────────────────────────────────────────────────────────
    // Domain Methods
    // ─────────────────────────────────────────────────────────────

    /**
     * Adds an item to the order.
     * Can only be called when the order is in PENDING status.
     *
     * @param item the order item to add
     * @throws IllegalStateException if order is not in PENDING status
     */
    public void addItem(OrderItem item) {
        if (this.status != OrderStatus.PENDING) {
            throw new IllegalStateException(
                "Cannot modify items for an order in status: " + this.status
            );
        }
        item.setOrder(this);
        this.items.add(item);
    }

    /**
     * Confirms the order after restaurant acknowledgment.
     * Transitions status from PENDING → CONFIRMED.
     *
     * @throws IllegalStateException if the order is not in PENDING status
     */
    public void confirm() {
        ensureStatus(OrderStatus.PENDING, "confirm");
        this.status = OrderStatus.CONFIRMED;
        this.confirmedAt = Instant.now();
    }

    /**
     * Marks the kitchen as having started preparing the order.
     * Transitions status from CONFIRMED → PREPARING.
     */
    public void startPreparing() {
        ensureStatus(OrderStatus.CONFIRMED, "start preparing");
        this.status = OrderStatus.PREPARING;
        this.preparingAt = Instant.now();
    }

    /**
     * Marks the order as ready for pickup or delivery.
     * Transitions status from PREPARING → READY.
     */
    public void markReady() {
        ensureStatus(OrderStatus.PREPARING, "mark as ready");
        this.status = OrderStatus.READY;
        this.readyAt = Instant.now();
    }

    /**
     * Marks the order as picked up and out for delivery.
     * Transitions status from READY → OUT_FOR_DELIVERY.
     */
    public void markOutForDelivery(UUID driverId, String driverName, String driverPhone) {
        ensureStatus(OrderStatus.READY, "mark out for delivery");
        this.status = OrderStatus.OUT_FOR_DELIVERY;
        this.pickedUpAt = Instant.now();
        this.driverId = driverId;
        this.driverName = driverName;
        this.driverPhone = driverPhone;
    }

    /**
     * Marks the order as successfully delivered.
     * Transitions status from OUT_FOR_DELIVERY → DELIVERED.
     */
    public void markDelivered() {
        ensureStatus(OrderStatus.OUT_FOR_DELIVERY, "mark as delivered");
        this.status = OrderStatus.DELIVERED;
        this.deliveredAt = Instant.now();
        this.actualDelivery = Instant.now();
        this.paymentStatus = PaymentStatus.PAID;
    }

    /**
     * Cancels the order with a reason.
     * Only possible from PENDING or CONFIRMED status.
     *
     * @param reason explanation for the cancellation
     * @throws IllegalStateException if the order cannot be cancelled in current status
     */
    public void cancel(String reason) {
        if (!isCancellable()) {
            throw new IllegalStateException(
                "Cannot cancel order in status: " + this.status +
                ". Only PENDING or CONFIRMED orders can be cancelled."
            );
        }
        this.status = OrderStatus.CANCELLED;
        this.cancelledAt = Instant.now();
        this.cancellationReason = reason;
    }

    /**
     * Processes a refund for the order.
     *
     * @param amount  the amount to refund (must not exceed total paid)
     * @param reason  the reason for the refund
     * @throws IllegalArgumentException if the refund amount exceeds the total
     */
    public void processRefund(BigDecimal amount, String reason) {
        if (amount.compareTo(this.totalAmount) > 0) {
            throw new IllegalArgumentException(
                "Refund amount " + amount + " exceeds order total " + this.totalAmount
            );
        }
        this.refundAmount = this.refundAmount.add(amount);
        this.refundReason = reason;
        this.paymentStatus = this.refundAmount.compareTo(this.totalAmount) >= 0
            ? PaymentStatus.REFUNDED
            : PaymentStatus.PARTIALLY_REFUNDED;
        if (this.status != OrderStatus.DELIVERED) {
            this.status = OrderStatus.REFUNDED;
        }
    }

    /**
     * Determines if this order can be cancelled by the customer.
     *
     * @return true if cancellation is allowed in the current status
     */
    public boolean isCancellable() {
        return this.status == OrderStatus.PENDING || this.status == OrderStatus.CONFIRMED;
    }

    /**
     * Calculates and validates the order total.
     * total = subtotal - discount + delivery_fee + service_fee + tax + tip
     *
     * @return the expected total amount
     */
    public BigDecimal calculateExpectedTotal() {
        return subtotal
            .subtract(discountAmount != null ? discountAmount : BigDecimal.ZERO)
            .subtract(promoDiscount != null ? promoDiscount : BigDecimal.ZERO)
            .add(deliveryFee != null ? deliveryFee : BigDecimal.ZERO)
            .add(serviceFee != null ? serviceFee : BigDecimal.ZERO)
            .add(taxAmount != null ? taxAmount : BigDecimal.ZERO)
            .add(tipAmount != null ? tipAmount : BigDecimal.ZERO);
    }

    private void ensureStatus(OrderStatus expected, String action) {
        if (this.status != expected) {
            throw new IllegalStateException(
                String.format("Cannot %s order. Expected status: %s, current: %s",
                    action, expected, this.status)
            );
        }
    }

    // ─────────────────────────────────────────────────────────────
    // Enums
    // ─────────────────────────────────────────────────────────────

    /** How the order will be fulfilled. */
    public enum OrderType {
        DELIVERY,         // Delivered to customer's address
        PICKUP,           // Customer collects from restaurant
        DINE_IN,          // Order placed at restaurant table
        INGREDIENT_KIT,   // Ingredients delivered for home cooking
        CATERING          // Bulk order for events
    }

    /** Lifecycle status of the order. */
    public enum OrderStatus {
        PENDING,            // Order placed, awaiting restaurant confirmation
        CONFIRMED,          // Restaurant confirmed the order
        PREPARING,          // Kitchen is preparing the order
        READY,              // Order is ready for pickup/delivery
        OUT_FOR_DELIVERY,   // Driver has picked up and is en route
        DELIVERED,          // Successfully delivered to customer
        CANCELLED,          // Order cancelled (by customer or restaurant)
        REFUNDED            // Order refunded after delivery dispute
    }

    /** Payment lifecycle status. */
    public enum PaymentStatus {
        PENDING,             // Payment authorized but not captured
        AUTHORIZED,          // Pre-authorized on card
        PAID,                // Payment fully captured
        FAILED,              // Payment failed
        PARTIALLY_REFUNDED,  // Partial refund processed
        REFUNDED             // Full refund processed
    }
}
